//
//  QuestionBank.swift
//  Flower App
//
//  Created for organizing questions by genre
//

import Foundation

struct QuestionBank {
    static func getAllQuestions() -> [QuestionGenre: [Question]] {
        return [
            .informational: [
                Question(text: "What's your favorite childhood memory?", type: .text, genre: .informational),
                Question(text: "What's something you've always wanted to learn?", type: .text, genre: .informational),
                Question(text: "What's your ideal way to spend a weekend?", type: .text, genre: .informational),
                Question(text: "What's a hobby you'd like to pick up?", type: .text, genre: .informational),
                Question(text: "What's your favorite book or movie and why?", type: .text, genre: .informational),
                Question(text: "What's something interesting about your family?", type: .text, genre: .informational),
                Question(text: "What's a skill you'd like to develop?", type: .text, genre: .informational),
                Question(text: "What's your favorite type of food or cuisine?", type: .text, genre: .informational),
                Question(text: "What's something you're curious about?", type: .text, genre: .informational),
                Question(text: "What's a place you've always wanted to visit?", type: .text, genre: .informational),
                Question(text: "What's your favorite season and why?", type: .text, genre: .informational),
                Question(text: "What's something that motivates you?", type: .text, genre: .informational),
                Question(text: "What's a goal you have for this year?", type: .text, genre: .informational),
                Question(text: "What's your favorite way to relax?", type: .text, genre: .informational),
                Question(text: "What's something you're grateful for today?", type: .text, genre: .informational),
            ],
            .romantic: [
                Question(text: "What's one thing you love about your partner?", type: .text, genre: .romantic),
                Question(text: "What's a memory that makes you happy together?", type: .text, genre: .romantic),
                Question(text: "What's something that made you feel loved today?", type: .text, genre: .romantic),
                Question(text: "What's your favorite thing to do together?", type: .text, genre: .romantic),
                Question(text: "What's a dream you share for your future?", type: .text, genre: .romantic),
                Question(text: "What's something that brings you closer?", type: .text, genre: .romantic),
                Question(text: "What's a quality you admire in your partner?", type: .text, genre: .romantic),
                Question(text: "What's a moment you want to remember forever?", type: .text, genre: .romantic),
                Question(text: "What's something romantic you'd like to do together?", type: .text, genre: .romantic),
                Question(text: "What's a way your partner makes you feel special?", type: .text, genre: .romantic),
                Question(text: "What's your favorite thing about being together?", type: .text, genre: .romantic),
                Question(text: "What's something that made you smile today about your partner?", type: .text, genre: .romantic),
                Question(text: "What's a way you want to express your love today?", type: .text, genre: .romantic),
                Question(text: "What's a romantic gesture that means a lot to you?", type: .text, genre: .romantic),
                Question(text: "What's something that makes your relationship special?", type: .text, genre: .romantic),
            ],
            .spicy: [
                Question(text: "What's something playful you'd like to try together?", type: .text, genre: .spicy),
                Question(text: "What's a fun challenge you want to do together?", type: .text, genre: .spicy),
                Question(text: "What's something that gets you excited about your partner?", type: .text, genre: .spicy),
                Question(text: "What's a flirty message you'd like to send?", type: .text, genre: .spicy),
                Question(text: "What's something adventurous you want to try?", type: .text, genre: .spicy),
                Question(text: "What's a playful game you'd like to play together?", type: .text, genre: .spicy),
                Question(text: "What's something that makes you feel attractive?", type: .text, genre: .spicy),
                Question(text: "What's a fun surprise you'd like to plan?", type: .text, genre: .spicy),
                Question(text: "What's something that sparks your interest?", type: .text, genre: .spicy),
                Question(text: "What's a playful activity you want to do together?", type: .text, genre: .spicy),
                Question(text: "What's something that makes you feel confident?", type: .text, genre: .spicy),
                Question(text: "What's a fun way you want to connect today?", type: .text, genre: .spicy),
                Question(text: "What's something exciting you're looking forward to?", type: .text, genre: .spicy),
                Question(text: "What's a playful way you want to tease your partner?", type: .text, genre: .spicy),
                Question(text: "What's something that makes you feel good about yourself?", type: .text, genre: .spicy),
            ],
            .relationship: [
                Question(text: "What's something you appreciate about your relationship?", type: .text, genre: .relationship),
                Question(text: "What's a goal you're working towards together?", type: .text, genre: .relationship),
                Question(text: "What's a challenge you've overcome together?", type: .text, genre: .relationship),
                Question(text: "What's something new you learned about your partner?", type: .text, genre: .relationship),
                Question(text: "What's a habit you want to build together?", type: .text, genre: .relationship),
                Question(text: "What's a way you want to grow together?", type: .text, genre: .relationship),
                Question(text: "What's something you want to try together?", type: .text, genre: .relationship),
                Question(text: "What's a tradition you want to start?", type: .text, genre: .relationship),
                Question(text: "What's something that makes your relationship unique?", type: .text, genre: .relationship),
                Question(text: "What's a way you support each other?", type: .text, genre: .relationship),
                Question(text: "What's something you're proud of as a couple?", type: .text, genre: .relationship),
                Question(text: "What's a way you communicate best?", type: .text, genre: .relationship),
                Question(text: "What's something you want to improve together?", type: .text, genre: .relationship),
                Question(text: "What's a way you make decisions together?", type: .text, genre: .relationship),
                Question(text: "What's something that strengthens your bond?", type: .text, genre: .relationship),
            ],
            .photo: [
                Question(text: "Share a photo of something that made you happy today", type: .photo, genre: .photo),
                Question(text: "Capture a moment you want to remember together", type: .photo, genre: .photo),
                Question(text: "Take a photo of something that represents your relationship", type: .photo, genre: .photo),
                Question(text: "Share a picture of something you're grateful for", type: .photo, genre: .photo),
                Question(text: "Capture something beautiful you saw today", type: .photo, genre: .photo),
                Question(text: "Share a photo of your favorite thing today", type: .photo, genre: .photo),
                Question(text: "Capture a moment that made you smile", type: .photo, genre: .photo),
                Question(text: "Take a photo of something that represents how you feel", type: .photo, genre: .photo),
                Question(text: "Share a picture of something that inspired you", type: .photo, genre: .photo),
                Question(text: "Capture something that made today special", type: .photo, genre: .photo),
                Question(text: "Take a selfie together", type: .photo, genre: .photo),
                Question(text: "Share a photo of your surroundings", type: .photo, genre: .photo),
                Question(text: "Capture something that reminds you of your partner", type: .photo, genre: .photo),
                Question(text: "Share a picture of something you created", type: .photo, genre: .photo),
                Question(text: "Take a photo of something that made you laugh", type: .photo, genre: .photo),
            ],
            .fun: [
                Question(text: "What's something that made you laugh today?", type: .text, genre: .fun),
                Question(text: "What's a funny memory you share?", type: .text, genre: .fun),
                Question(text: "What's something silly you want to do together?", type: .text, genre: .fun),
                Question(text: "What's a joke or funny story you want to share?", type: .text, genre: .fun),
                Question(text: "What's something playful you did today?", type: .text, genre: .fun),
                Question(text: "What's a fun fact you learned recently?", type: .text, genre: .fun),
                Question(text: "What's something that brings you joy?", type: .text, genre: .fun),
                Question(text: "What's a game you'd like to play together?", type: .text, genre: .fun),
                Question(text: "What's something that surprised you today?", type: .text, genre: .fun),
                Question(text: "What's a fun tradition you have together?", type: .text, genre: .fun),
                Question(text: "What's something that makes you smile?", type: .text, genre: .fun),
                Question(text: "What's a fun activity you want to try?", type: .text, genre: .fun),
                Question(text: "What's something that entertained you today?", type: .text, genre: .fun),
                Question(text: "What's a fun challenge you want to do?", type: .text, genre: .fun),
                Question(text: "What's something that made your day better?", type: .text, genre: .fun),
            ],
            .deep: [
                Question(text: "What's something that inspires you?", type: .text, genre: .deep),
                Question(text: "What's a fear you've overcome?", type: .text, genre: .deep),
                Question(text: "What's something you've learned about yourself recently?", type: .text, genre: .deep),
                Question(text: "What's a way you want to grow as a person?", type: .text, genre: .deep),
                Question(text: "What's something that challenges you?", type: .text, genre: .deep),
                Question(text: "What's a value that's important to you?", type: .text, genre: .deep),
                Question(text: "What's something you're proud of?", type: .text, genre: .deep),
                Question(text: "What's a dream you're working towards?", type: .text, genre: .deep),
                Question(text: "What's something that changed your perspective?", type: .text, genre: .deep),
                Question(text: "What's a way you want to make a difference?", type: .text, genre: .deep),
                Question(text: "What's something that makes you feel grateful?", type: .text, genre: .deep),
                Question(text: "What's a lesson you've learned recently?", type: .text, genre: .deep),
                Question(text: "What's something that gives you purpose?", type: .text, genre: .deep),
                Question(text: "What's a way you want to impact others?", type: .text, genre: .deep),
                Question(text: "What's something meaningful to you?", type: .text, genre: .deep),
            ]
        ]
    }
}

